# Site settings
title: Vallilan lennokkikerho ry
email: vallilanlennokkikerho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vallilan lennokkikerho ry eli Valkka on vuonna 1937 perustettu lennokkikerho, jonka laajassa jäsenistössä on lähes kaikki lennokkiluokat edustettuina.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vallilanlennokkikerho.fi/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
